var productData = [
    {
        img: "https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/6/1/618b193lakme00000110_0.jpg",
        name: "Lakme Absolute Spotlight Lip Gloss",
        price: "608",
        discount_price:"765",
        rating: "4.5",
        brand: "Lakme",
        category: "lipstick",
        color: "Pink",
    },
    {
        img: "https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/9/5/950474eLAK_ABSEYEPL_1.jpg",
        name: "Lakme Absolute Spotlight Eye Shadow Palette - Stilettos",
        price: "896",
        discount_price:"995",
        rating: "5",
        brand: "Lakme",
        category: "makeup",
        color: "Pink",
    },
    {
        img: "https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/2/2/22342_h_1_2.jpg",
        name: "Lakme Eyeconic Curling Mascara",
        price: "375",
        discount_price:"465",
        rating: "5",
        brand: "Lakme",
        category: "makeup",
        color: "black",
    },
    {
        img: "https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/l/a/lakm_-absolute-blur-perfect-makeup-primer.jpg",
        name: "Lakme Absolute Blur Perfect Makeup Primer",
        price: "675",
        discount_price:"750",
        rating: "4",
        brand: "Lakme",
        category: "Personal Care",
        color: "black",
    },
    {
        img: "https://images-static.nykaa.com/media/catalog/product/tr:w-200,h-200,cm-pad_resize/l/k/lkm_matrev_1.jpg",
        name: "Lakme A-Mate Revitalizing Lip Color",
        price: "800",
        discount_price:"850",
        rating: "4",
        brand: "Lakme",
        category: "Lipstick",
        color: "red",
    },
]